### PR TITLE
Set default to empty dict instead of using try/except.

### PR DESCRIPTION
**Pull request by bebosudo**
Solving issue #132 .

Easy enough ;-)

### CODE REVIEW

**Comment by nlsdfnbch** [comment]
Good start - but there's more to go - want to pick those up as well? They're not all called `params`, I'm afraid.  Feel free to change that as well!

**Comment by bebosudo** [comment]
Found another one.

For future reference:
`$ grep -n -R -B1 -A2 '\.pop(' bitex`

**Comment by bebosudo** [comment]
Do you mean you want to change also occurrencies like these, in order to return an empty dict in case of a missing value?
https://github.com/Crypto-toolbox/bitex/blob/4e38dc565ab9d65020dc82e43b21bd8a1f23ccf7/bitex/api/REST/bitfinex.py#L40

**Comment by nlsdfnbch** [comment]
@bebosudo, yes those too!

But the `try/except` block is also present in `bter`, `kraken` and the remaining API classes. Just have a look through them, you'll find them :)

**Comment by bebosudo** [comment]
I was searching only for `pop`ping operations, but a search on `KeyError` occurencies made me found many other cases.
Hope the issue is solved :-)

**Pull request merged**
